<?php

/**
 * Implements hook_permission().
 */
function tfa_basic_permission() {
  return array(
    'setup own tfa' => array(
      'title' => t('Set up TFA for account'),
      'description' => t('Allow users to set up TFA for their account. Users with "administer users" permission can edit other account\'s TFA.'),
    ),
  );
}

/**
 * Implements hook_config_info().
 */
function tfa_basic_config_info() {
  $prefixes['tfa_basic.settings'] = array(
    'label' => t('TFA Basic settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_library_info().
 */
function tfa_basic_library_info() {
  $items = array();
  $items['qrcodejs'] = array(
    'title' => 'QRCode.js',
    'website' => 'https://github.com/davidshimjs/qrcodejs',
    'version' => '1.0',
    'js' => array(
      backdrop_get_path('module', 'tfa_basic') . '/libraries/qrcodejs/qrcode.min.js' => array(),
    ),
  );
  return $items;
}

/**
 * Implements hook_autoload_info().
 */
function tfa_basic_autoload_info() {
  return array(
    'TfaTotp' => 'includes/tfa_totp.inc',
    'TfaTotpSetup' => 'includes/tfa_totp.inc',
    'TfaTrustedBrowser' => 'includes/tfa_trusted_browser.inc',
    'TfaTrustedBrowserSetup' => 'includes/tfa_trusted_browser.inc',
    'TfaBasicRecoveryCode' => 'includes/tfa_recovery.inc',
    'TfaBasicRecoveryCodeSetup' => 'includes/tfa_recovery.inc',
    'TfaBasicEmail' => 'includes/tfa_email.inc',
    'TfaBasicEmailSetup' => 'includes/tfa_email.inc',
    'TfaBasicHelp' => 'includes/tfa_help.inc',
    // Forked from https://github.com/PHPGangsta/GoogleAuthenticator
    'SebastianDevs\SimpleAuthenticator' => 'includes/simplethenticator/SimpleAuthenticator.php',
  );
}

/**
 * Implements hook_menu().
 */
function tfa_basic_menu() {
  $items = array();

  $items['user/%user/security/tfa'] = array(
    'title' => 'Security',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('tfa_basic_overview', 1),
    'access callback' => 'tfa_basic_setup_access',
    'access arguments' => array(1, 'setup own tfa'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'tfa_basic.pages.inc',
  );
  $items['user/%user/security/tfa/disable'] = array(
    'title' => 'TFA disable',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('tfa_basic_disable_form', 1),
    'access callback' => 'tfa_basic_setup_access',
    'access arguments' => array(1, 'setup own tfa'),
    'type' => MENU_CALLBACK,
    'file' => 'tfa_basic.pages.inc',
  );
  $items['user/%user/security/tfa/app-setup'] = array(
    'title' => 'TFA setup',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('tfa_basic_setup_form', 1, 'tfa_basic_totp'),
    'access callback' => 'tfa_basic_setup_access',
    'access arguments' => array(1, 'setup own tfa'),
    'type' => MENU_CALLBACK,
    'file' => 'tfa_basic.pages.inc',
  );
  $items['user/%user/security/tfa/trusted-browsers'] = array(
    'title' => 'TFA setup',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('tfa_basic_setup_form', 1, 'tfa_basic_trusted_browser'),
    'access callback' => 'tfa_basic_setup_access',
    'access arguments' => array(1, 'setup own tfa'),
    'type' => MENU_CALLBACK,
    'file' => 'tfa_basic.pages.inc',
  );
  $items['user/%user/security/tfa/recovery-codes'] = array(
    'title' => 'TFA setup',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('tfa_basic_setup_form', 1, 'tfa_basic_recovery_code'),
    'access callback' => 'tfa_basic_setup_access',
    'access arguments' => array(1, 'setup own tfa'),
    'type' => MENU_CALLBACK,
    'file' => 'tfa_basic.pages.inc',
  );
  $items['user/%user/security/tfa/recovery-codes-list'] = array(
    'title' => 'TFA - Unused recovery codes',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('tfa_basic_setup_form', 1, 'recovery_codes_list'),
    'access callback' => 'tfa_basic_setup_access',
    'access arguments' => array(1, 'setup own tfa'),
    'type' => MENU_CALLBACK,
    'file' => 'tfa_basic.pages.inc',
  );
  $items['user/%user/security/tfa/email-setup'] = array(
    'title' => 'TFA setup',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('tfa_basic_setup_form', 1, 'tfa_basic_email'),
    'access callback' => 'tfa_basic_setup_access',
    'access arguments' => array(1, 'setup own tfa'),
    'type' => MENU_CALLBACK,
    'file' => 'tfa_basic.pages.inc',
  );

  return $items;
}

/**
 * Access control.
 *
 * @param object $account
 * @param string $permission
 * @return bool
 */
function tfa_basic_setup_access($account, $permission = '') {
  $administer_users = user_access('administer users') && $account->uid > 0;
  $is_account = ($GLOBALS['user']->uid == $account->uid);

  return ($is_account && user_access($permission, $account)) || $administer_users;
}

/**
 * Implements hook_cron().
 */
function tfa_basic_cron() {
  $config = config('tfa_basic.settings');

  // Delete trusted browser entries older than expiration.
  $expiration = $config->get('tfa_basic_trust_cookie_expiration');

  $num_deleted = db_delete('tfa_trusted_browser')
    ->condition('created', REQUEST_TIME - $expiration, '<')
    ->execute();
  if ($num_deleted) {
    watchdog('tfa_basic', 'Removed !num TFA trusted browsers older than !time', array('!num' => $num_deleted, '!time' => REQUEST_TIME - $expiration), WATCHDOG_INFO);
  }

  // Delete accepted codes older than expiration.
  $accepted_expiration = $config->get('tfa_basic_accepted_code_expiration');
  db_delete('tfa_accepted_code')
    ->condition('time_accepted', REQUEST_TIME - $accepted_expiration, '<')
    ->execute();
}

/**
 * Implements hook_tfa_api().
 */
function tfa_basic_tfa_api() {
  return array(
    'tfa_basic_totp' => array(
      'class' => 'TfaTotp',
      'name' => 'TOTP',
    ),
    'tfa_basic_trusted_browser' => array(
      'class' => 'TfaTrustedBrowser',
      'name' => 'Trusted Browsers',
    ),
    'tfa_basic_recovery_code' => array(
      'class' => 'TfaBasicRecoveryCode',
      'name' => 'Recovery Codes',
    ),
    'tfa_basic_email' => array(
      'class' => 'TfaBasicEmail',
      'name' => 'Email',
    ),
    'tfa_basic_help' => array(
      'class' => 'TfaBasicHelp',
      'name' => 'Help page',
    ),
  );
}

/**
 * Create TfaTotp plugin.
 *
 * @param array $context
 * @return TfaTotp
 */
function tfa_basic_totp_create($context) {
  return new TfaTotp($context);
}

/**
 * Create TfaTrustedBrowser plugin.
 *
 * @param array $context
 * @return TfaTrustedBrowser
 */
function tfa_basic_trusted_browser_create($context) {
  return new TfaTrustedBrowser($context);
}

/**
 * Create TfaBasicRecoveryCode plugin.
 *
 * @param array $context
 * @return TfaBasicRecoveryCode
 */
function tfa_basic_recovery_code_create($context) {
  return new TfaBasicRecoveryCode($context);
}

/**
 * Create TfaBasicEmail plugin.
 *
 * @param array $context
 * @return TfaBasicEmail
 */
function tfa_basic_email_create($context) {
  return new TfaBasicEmail($context);
}

/**
 * Alters tfa_context array to set plugins from user settings.
 */
function tfa_basic_tfa_context_alter(&$context) {
  // $context can be empty during beginning of TFA process.
  if (empty($context)) {
    return;
  }
}

/**
 * Implements hook_tfa_ready_require().
 */
function tfa_basic_tfa_ready_require($account) {
  if (tfa_basic_tfa_required($account)) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Whether TFA is required for the account.
 *
 * @param object $account
 *
 * @return bool
 */
function tfa_basic_tfa_required($account) {
  $required = &backdrop_static(__FUNCTION__);
  if (isset($required)) {
    return $required;
  }
  $required = FALSE;
  $required_roles = config_get('tfa_basic.settings', 'tfa_basic_roles_require');
  if (!empty($required_roles)) {
    foreach ($required_roles as $enabled) {
      if ($enabled && in_array($enabled, $account->roles)) {
        $required = TRUE;
        break;
      }
    }
  }
  return $required;
}

/**
 * Implements hook_tfa_skip_require().
 */
function tfa_basic_tfa_skip_require($account) {
  if (!tfa_basic_skip_required($account)) {
    return FALSE;
  }
  return TRUE;
}

/**
 * Whether TFA requirement can be skipped for the account.
 *
 * @param User $account
 *
 * @return bool
 */
function tfa_basic_skip_required($account) {
  $skipped = &backdrop_static(__FUNCTION__);
  if (isset($skipped)) {
    return $skipped;
  }

  $skipped = FALSE;

  $remaining = tfa_basic_remaining_skips($account);
  if ($remaining) {
    $skipped = TRUE;
    tfa_basic_skip_verification_message($remaining - 1, $account);
    tfa_basic_has_skipped($account);
  }
  else {
    $skipped = FALSE;
    tfa_basic_require_verification_message();
  }

  return $skipped;
}

/**
 * Remaining number of allowed logins without setting up TFA.
 *
 * @param User $account
 * @return int|false
 *   FALSE if users are never allowed to log in without setting up TFA.
 *   The remaining number of times user may log in without setting up TFA.
 */
function tfa_basic_remaining_skips($account) {
  $allowed_skips = intval(config_get('tfa_basic.settings', 'tfa_basic_validation_skip'));
  // Skipping TFA setup is not allowed.
  if (!$allowed_skips) {
    return FALSE;
  }

  $user_tfa = tfa_basic_get_tfa_data($account);
  $validation_skipped = isset($user_tfa['data']['validation_skipped']) ? $user_tfa['data']['validation_skipped'] : 0;
  return max(0, $allowed_skips - $validation_skipped);
}

/**
 * Increment the count of user logins without setting up TFA.
 *
 * @param User $account
 */
function tfa_basic_has_skipped($account) {
  $user_tfa = tfa_basic_get_tfa_data($account);
  $validation_skipped = isset($user_tfa['data']['validation_skipped']) ? $user_tfa['data']['validation_skipped'] : 0;
  $new_count = $validation_skipped + 1;
  tfa_basic_setup_save_data($account, array('validation_skipped' => $new_count));
}

/**
 * Set the require verification message.
 */
function tfa_basic_require_verification_message() {
  backdrop_set_message(t('Login disallowed. You are required to set up two-factor authentication. Please contact a site administrator.'), 'error', FALSE);
}

/**
 * Set the skip verification message.
 *
 * @param int $remaining
 */
function tfa_basic_skip_verification_message($remaining, $account) {
  $messages = backdrop_get_messages('error');
  // Since the tfa_basic module sets the error message this will be set
  // but check just in case.
  if (isset($messages['error'])) {
    foreach ($messages['error'] as $key => $message) {
      if ($message != t('Login disallowed. You are required to set up two-factor authentication. Please contact a site administrator.')) {
        // Re-add any other error messages we might have in the queue.
        backdrop_set_message($message, 'error');
      }
    }
  }

  // Notify user that they are required to setup TFA.
  $tfa_setup_link = url('user/' . $account->uid . '/security/tfa');
  $message = format_plural($remaining, 'You are required to <a href="!link">setup two-factor authentication</a>. You have 1 attempt left. After this you will be unable to login.', 'You are required to <a href="!link">setup two-factor authentication</a>. You have @remaining attempts left. After this you will be unable to login.', array('@remaining' => $remaining, '!link' => $tfa_setup_link));
  backdrop_set_message($message, 'warning', FALSE);
}

/**
 * Get mobile number for an account.
 *
 * @param object $account
 *   User account object.
 *
 * @return string|FALSE
 *   Mobile phone number or FALSE if not set.
 */
function tfa_basic_get_mobile_number($account) {
  $phone_field = config_get('tfa_basic.settings', 'tfa_basic_phone_field');
  $number = FALSE;
  // Note, set tfa_basic_phone_field to FALSE to avoid using account field as
  // storage.
  if (!empty($phone_field)) {
    if (!empty($account->{$phone_field}[LANGUAGE_NONE][0]['value'])) {
      $number = $account->{$phone_field}[LANGUAGE_NONE][0]['value'];
    }
  }
  $alterable = array(
    'account' => $account,
    'number' => $number,
  );
  // Allow other modules to supply the mobile number for this account.
  backdrop_alter('tfa_basic_get_mobile_number', $alterable);
  return $alterable['number'];
}

/**
 * Update mobile number on account.
 *
 * @param object $account
 * @param string $number
 */
function tfa_basic_set_mobile_number($account, $number) {
  $phone_field = config_get('tfa_basic.settings', 'tfa_basic_phone_field');
  if ($phone_field !== FALSE) {
    if (isset($account->{$phone_field})) {
      $edit = array(
        $phone_field => array(LANGUAGE_NONE => array(0 => array('value' => $number))),
      );
      user_save($account, $edit);
    }
  }
  $alterable = array(
    'account' => $account,
    'number' => $number,
  );
  // Allow other modules to set the mobile number for this account.
  backdrop_alter('tfa_basic_set_mobile_number', $alterable);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function tfa_basic_form_tfa_form_alter(&$form, &$form_state, $form_id) {
  // Add validation handler for fallback awareness.
  $form['#validate'][] = '_tfa_basic_form_validate';
}

/**
 * Validation handler to encourage use of fallback if there are form errors.
 */
function _tfa_basic_form_validate($form, &$form_state) {
  $errors = form_get_errors();
  if (!empty($errors) && !empty($form_state['values']['code']) && isset($form['actions']['fallback'])) {
    backdrop_set_message(t("If you are having trouble click \"Can't access your account?\" for further authentication options."), 'warning');
  }
}

/**
 * Get TFA data for an account.
 *
 * @param object $account
 *   User account.
 *
 * @return array
 *   TFA data.
 *
 * @code
 *   array(
 *     'status' => TRUE,
 *     'data' => array(
 *       'primary' => 'app',
 *       'email' => FALSE,
 *     ),
 *   )
 * @endcode
 */
function tfa_basic_get_tfa_data($account) {
  $result = db_query("SELECT status, saved, data FROM {tfa_user_settings} WHERE uid = :uid", array(':uid' => $account->uid))->fetchAssoc();
  if (!empty($result)) {
    $data = array();
    if (!empty($result['data'])) {
      $data = json_decode($result['data'], TRUE);
    }
    $tfa = array(
      'status' => $result['status'] == '1' ? TRUE : FALSE,
      'saved' => $result['saved'],
      'data' => $data,
    );
    return $tfa;
  }
  return array();
}

/**
 * Save TFA settings for an account.
 *
 * @param object $account
 * @param array $data TFA data
 * @code
 *   array(
 *     'plugins' => ['tfa_basic_totp'],
 *     'email' => FALSE,
 *     'validation_skipped' => 1,
 *     'status' => TRUE,
 *   )
 * @endcode
 */
function tfa_basic_setup_save_data($account, $data = array()) {
  // Check if existing data and update.
  $existing = tfa_basic_get_tfa_data($account);
  $status = 1;
  if (!empty($existing['data'])) {
    $tfa_data = $existing['data'];
  }
  else {
    $status = 0;
    $tfa_data = array(
      'plugins' => '',
      'email' => FALSE,
      'validation_skipped' => 0,
    );
  }
  if (isset($data['plugins'])) {
    $tfa_data['plugins'] = $data['plugins'];
  }
  if (isset($data['email'])) {
    $tfa_data['email'] = $data['email'];
  }
  if (isset($data['validation_skipped'])) {
    $tfa_data['validation_skipped'] = $data['validation_skipped'];
  }
  if (isset($existing['status'])) {
    $status = $existing['status'];
  }
  if (isset($data['status'])) {
    $status = $data['status'];
    if ($data['status'] === FALSE) {
      $tfa_data = array();
    }
  }

  $record = array(
    'uid' => $account->uid,
    'saved' => REQUEST_TIME,
    'status' => $status,
    'data' => json_encode($tfa_data),
  );
  if (!empty($existing)) {
    backdrop_write_record('tfa_user_settings', $record, 'uid');
  }
  else {
    backdrop_write_record('tfa_user_settings', $record);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function tfa_basic_form_tfa_admin_settings_alter(&$form, &$form_state, $form_id) {
  global $cookie_domain;

  $config = config('tfa_basic.settings');

  $form['tfa_basic_validation_skip'] = array(
    '#type' => 'number',
    '#title' => t('Skip validation'),
    '#description' => t('Number of times a user without having set up TFA validation can login.'),
    '#default_value' => (int) $config->get('tfa_basic_validation_skip'),
    '#min' => 0,
    '#max' => 10,
  );

  $form['required_tfa_roles'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Roles required to have set up TFA'),
    '#description' => t("Login will be denied to an account without TFA setup and any matching role."),
    '#options' => user_roles(TRUE),
    '#default_value' => $config->get('tfa_basic_roles_require'),
  );

  // Add cookie domain field to TFA admin settings.
  $tfa_basic_cookie_domain = $config->get('tfa_basic_cookie_domain');
  $form['tfa_basic_cookie_domain'] = array(
    '#type' => 'textfield',
    '#title' => t('Cookie domain'),
    '#default_value' => !empty($tfa_basic_cookie_domain) ? $tfa_basic_cookie_domain : $cookie_domain,
    '#description' => t('Domain to set for the trusted browser TFA cookie.'),
    '#states' => array(
      'visible' => array(
        ':input[name="tfa_login[tfa_basic_trusted_browser]"]' => array('checked' => TRUE)
      )
    ),
  );

  $form['tfa_fallback']['tfa_basic_help']['weight']['#default_value'] = 10;
  $form['tfa_fallback']['tfa_basic_help']['weight']['#disabled'] = TRUE;
  $form['tfa_basic_help_text'] = array(
    '#type' => 'textfield',
    '#title' => t('Help page text'),
    '#default_value' => $config->get('tfa_basic_help_text'),
    '#description' => t('Text to display on help page. Plain text only.'),
    '#states' => array(
      'visible' => array(
        array(
          array(':input[name="tfa_fallback[tfa_basic_help][enable]"]' => array('checked' => TRUE)),
          'or',
          array(':input[name="tfa_validate"]' => array('value' => 'tfa_basic_help'))
        )
      )
    ),
  );

  $form['#validate'][] = 'tfa_basic_form_validate';
  $form['#submit'][] = 'tfa_basic_form_submit';
}

/**
 * Validation for TFA admin settings alter.
 */
function tfa_basic_form_validate($form, &$form_state) {
  $login = array();
  $values = $form_state['values'];
  if (!empty($values['tfa_login'])) {
    foreach ($values['tfa_login'] as $key => $enabled) {
      if ($enabled) {
        $login[] = $key;
      }
    }

    if (!empty($login) && in_array('tfa_basic_trusted_browser', $login) && empty($values['tfa_basic_cookie_domain'])) {
      form_set_error('tfa_basic_cookie_domain', t('Cookie domain is required if Trusted Browser plugin is enabled.'));
    }
  }
}

/**
 * Submit for TFA admin settings alter.
 */
function tfa_basic_form_submit($form, &$form_state) {
  $config = config('tfa_basic.settings');
  if (isset($form_state['values']['tfa_basic_validation_skip'])) {
    $config->set('tfa_basic_validation_skip', $form_state['values']['tfa_basic_validation_skip']);
  }
  if (!empty($form_state['values']['tfa_basic_cookie_domain'])) {
    $config->set('tfa_basic_cookie_domain', $form_state['values']['tfa_basic_cookie_domain']);
  }
  if (!empty($form_state['values']['tfa_basic_help_text'])) {
    $config->set('tfa_basic_help_text', $form_state['values']['tfa_basic_help_text']);
  }
  $config->set('tfa_basic_roles_require', $form_state['values']['required_tfa_roles']);
  $config->save();
}

/**
 * Implements hook_mail().
 */
function tfa_basic_mail($key, &$message, $params) {
  switch ($key) {
    case 'tfa_basic_tfa_enabled':
      $message['subject'] = t('Your @site_name account now has two-factor authentication', array('@site_name' => config_get('system.core', 'site_name')));
      $message['body']['body'] = tfa_basic_tfa_enabled_body($message, $params);
      break;

    case 'tfa_basic_disabled_configuration':
      $message['subject'] = t('Your @site_name account no longer has two-factor authentication', array('@site_name' => config_get('system.core', 'site_name')));
      $message['body']['body'] = tfa_basic_tfa_disabled_body($message, $params);
      break;

    case 'tfa_basic_email':
      $message['subject'] = t('Verification code for your @site_name account', array('@site_name' => config_get('system.core', 'site_name')));
      $message['body']['body'] = tfa_basic_tfa_email_message_body($message, $params);
      break;
  }
}

/**
 * Returns text appropriate for an email when someone has enabled tfa.
 *
 * @param array $message
 *   The message, must include the language.
 * @param array $params
 *   Parameters from backdrop_mail. Must include the account.
 *
 * @return string
 *   Message body.
 */
function tfa_basic_tfa_enabled_body($message, $params) {
  $text = t("[user:name],

Thanks for configuring two-factor authentication on your @site_name account!

This additional level of security will help to ensure that only you are able to log in to your account.

If you ever lose the device you configured, you should act quickly to delete its association with this account.

-- @site_name team", array('@site_name' => config_get('system.core', 'site_name')));

  return token_replace($text, array('user' => $params['account']), array('language' => $message['language'], 'sanitize' => FALSE, 'clear' => TRUE));
}

/**
 * Returns text appropriate for an email when someone has disabled tfa.
 *
 * @param array $message
 *   The message, must include the language.
 * @param array $params
 *   Parameters from backdrop_mail. Must include the account.
 *
 * @return string
 *   Message body.
 */
function tfa_basic_tfa_disabled_body($message, $params) {
  $text = t("[user:name],

Two-factor authentication has been disabled on your account.

If you did not take this action, please contact a site administrator immediately.

-- @site_name team", array('@site_name' => config_get('system.core', 'site_name')));

  return token_replace($text, array('user' => $params['account']), array('language' => $message['language'], 'sanitize' => FALSE, 'clear' => TRUE));
}

/**
 * Returns text appropriate for an email when someone has disabled tfa.
 *
 * @param array $message
 *   The message, must include the language.
 * @param array $params
 *   Parameters from backdrop_mail. Must include the account.
 *
 * @return string
 *   Message body.
 */
function tfa_basic_tfa_email_message_body($message, $params) {
  $langcode = $message['language']->langcode;
  $args = array('@site_name' => config_get('system.core', 'site_name'), '!code' => $params['code']);
  $text = config('tfa_basic.settings')->getTranslated('tfa_basic_email_message_text', $args, array('langcode' => $langcode));
  $variables = array('user' => $params['account']);
  return token_replace($text, $variables, array('language' => $message['language'], 'sanitize' => FALSE, 'clear' => TRUE));
}
